#[allow(unused)]
use std::io::Write;
#[cfg(feature = "reg-config")]
use st_mems_reg_config_conv::parser;
#[cfg(feature = "reg-config")]
use std::path::Path;

fn main() {
    #[cfg(feature = "generate-memory-x")]
    {
        #[cfg(feature = "memory-x-512-96")]
        let (flash_size, ram_size) = (512, 96);

        let out_dir = std::path::PathBuf::from(std::env::var_os("OUT_DIR").unwrap());
        let dest = out_dir.join("memory.x");

        // Generate the memory.x content dynamically
        let script = format!(
            r#"
    /* Auto-generated by build.rs */
    /* NOTE 1 K = 1 KiBi = 1024 bytes */
    /* Adjust ORIGIN addresses if needed for your MCU */

    MEMORY
    {{
      FLASH : ORIGIN = 0x08000000, LENGTH = {flash}K
      RAM   : ORIGIN = 0x20000000, LENGTH = {ram}K
    }}
    "#,
            flash = flash_size,
            ram = ram_size,
        );

        std::fs::File::create(&dest).unwrap().write_all(script.as_bytes()).unwrap();

        // Tell rustc to add OUT_DIR to the linker search path
        println!("cargo:rustc-link-search={}", out_dir.display());
        println!("cargo:rerun-if-changed=memory.x");
    }

    // Specify linker arguments
    // `--nmagic` is required if memory section addresses are not aligned to 0x10000,
    // for example the FLASH and RAM sections in your `memory.x`.
    // See https://github.com/rust-embedded/cortex-m-quickstart/pull/95
    println!("cargo:rustc-link-arg=--nmagic");

    // Set the linker script to the one provided by cortex-m-rt.
    println!("cargo:rustc-link-arg=-Tlink.x");
    println!("cargo:rustc-link-arg=-Tdefmt.x");
}
